### PR TITLE
HPCC-19321 Dataframe example

### PR DESCRIPTION
**Pull request by johnholt**
Example in Scala using the Dataframe support.  This example runs the ML version (not MLLib) of Logistic Regression on the Iris dataset.

Signed-off-by: johnholt <john.d.holt@lexisnexisrisk.com>

### CODE REVIEW

**Comment by richardkchapman** [comment]
typo in commit message (sing should say using)

**Comment by johnholt** [comment]
Typo fixed.  Thanks.

**Comment by richardkchapman** [comment]
You fixed the github message (which is a copy of the info in the commit) but not the commit itself.

**Comment by johnholt** [comment]
This time I did a "reword" with an interactive rebase and pushed again.  I did not realize those were separate texts.

**Pull request merged**
