### PR TITLE
JAPI-407 Add JavaDoc descriptions to classes to Spark-HPCC

### PR DESCRIPTION
**Pull request by jpmcmu**
Signed-off-by: James McMullan <James.McMullan@lexisnexis.com>

### CODE REVIEW

**Comment by jpmcmu** [comment]
@rpastrana please review

**Review by rpastrana — COMMENTED** [review]
@jpmcmu looks good. Perhaps outside the scope of this issue, but I noticed the spark-hpcc javadoc includes some of the packages we filtered out in dfsclient/wsclient.
Can you add this to the pom?
<excludePackageNames>org.hpccsystems.ws.client.gen.*:org.hpccsystems.ws.client.antlr.*:org.hpccsystems.ws.client.wrappers.gen.*:org.hpccsystems.ws.client.extended.*</excludePackageNames>

**Comment by jpmcmu** [comment]
@rpastrana updated the excluded packages in the javadocs

**Review by rpastrana — APPROVED** [review]
@jpmcmu looks good.

**Pull request merged**
