### PR TITLE
SPARK-HPCC Branch 7.4.0 Gold

### PR DESCRIPTION
**Pull request by rpastrana**
Signed-off-by: Pastrana, Rodrigo <rodrigo.pastrana@lexisnexis.com>

### CODE REVIEW

**Comment by rpastrana** [comment]
@Michael-Gardner please review

**Comment by Michael-Gardner** [comment]
@rpastrana looks good

**Comment by rpastrana** [comment]
@richardkchapman please merge as part of 7.4.0 gold release

**Comment by rpastrana** [comment]
@richardkchapman please merge

**Pull request merged**
