### PR TITLE
HPCC-22333 Update Master pom to 7.4.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by rpastrana**
Signed-off-by: Pastrana, Rodrigo <rodrigo.pastrana@lexisnexis.com>

### CODE REVIEW

**Comment by rpastrana** [comment]
@Michael-Gardner please review

**Comment by Michael-Gardner** [comment]
@rpastrana looks good.  So confirming we're going to 1.4.0 for the commons package?

**Comment by rpastrana** [comment]
yes commons master is at 1.4.0-SNAPSHOT: https://github.com/hpcc-systems/HPCC-JAPIs/blob/master/commons-hpcc/pom.xml

**Comment by rpastrana** [comment]
@richardkchapman please merge

**Pull request merged**
