### PR TITLE
HPCC4J-625 SparkHPCC: Path support Databricks URI requirements

### PR DESCRIPTION
**Pull request by jpmcmu**
- Allowed path used in Datasource API to formatted as URIs to fix Databricks issue

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

### CODE REVIEW

**Comment by jpmcmu** [comment]
@rpastrana Please review. Note: you can click view file to see the rendered notebook changes from the PR.

**Comment by jpmcmu** [comment]
@rpastrana pushed up code review changes. Will squash if it looks good

**Review by rpastrana — APPROVED** [review]
@jpmcmu looks good. I did notice a minor issue w/ one the messages. Once resolved, lets squash

**Comment by jpmcmu** [comment]
@rpastrana Good catch, not sure how that occurred. Resaved the notebook and that fixed the issue

**Pull request merged**
