### PR TITLE
HPCC-19758 Provide copyright header and cleanup

### PR DESCRIPTION
**Pull request by rpastrana**
- Adds apache 2 2018 license headers
- Organizes import statements
- Removes author entries

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexis.com>

### CODE REVIEW

**Comment by rpastrana** [comment]
@johnholt please review

**Comment by rpastrana** [comment]
the "organizing" of the imports is done automatically by an Eclipse feature and shouldn't have any functional affect. It removes un-used imports, and I think it expands package.* to package.classname .
The tests ran successfully.

**Comment by rpastrana** [comment]
@johnholt did another quick pass and didn't see any issues w/ the imports.

**Comment by johnholt** [comment]
Sounds good to me then.  Let's make sure that we don't run the import thing against any Scala code without some through testing unless the tool says that it likes Scala.

**Comment by rpastrana** [comment]
@richardkchapman please merge

**Pull request merged**
