### PR TITLE
HPCC-20580 Track DAFILESERV trx codes

### PR DESCRIPTION
**Pull request by rpastrana**
- Creates RFCCodes class with all known dafilesrv codes
- Handles 2 file access expiry error codes
- Allows developers to overwrite default expiry

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexis.com>

### CODE REVIEW

**Comment by rpastrana** [comment]
@jpmcmu please review

**Comment by rpastrana** [comment]
@jpmcmu one last look please.

**Comment by jpmcmu** [comment]
@rpastrana looks good

**Comment by rpastrana** [comment]
@richardkchapman please merge

**Pull request merged**
